PRODUCT_VERSION_MAJOR = 9
PRODUCT_VERSION_MINOR = 0

ifeq ($(SUPERIOR_VERSION_APPEND_TIME_OF_DAY),true)
    SUPERIOR_BUILD_DATE := $(shell date -u +%Y%m%d_%H%M%S)
else
    SUPERIOR_BUILD_DATE := $(shell date -u +%Y%m%d)
endif

# Set SUPERIOR_BUILDTYPE from the env RELEASE_TYPE, for jenkins compat

ifndef SUPERIOR_BUILDTYPE
    ifdef RELEASE_TYPE
        # Starting with "SUPERIOR_" is optional
        RELEASE_TYPE := $(shell echo $(RELEASE_TYPE) | sed -e 's|^SUPERIOR_||g')
        SUPERIOR_BUILDTYPE := $(RELEASE_TYPE)
    endif
endif

# Filter out random types, so it'll reset to UNOFFICIAL
ifeq ($(filter RELEASE NIGHTLY SNAPSHOT EXPERIMENTAL,$(SUPERIOR_BUILDTYPE)),)
    SUPERIOR_BUILDTYPE := UNOFFICIAL
    SUPERIOR_EXTRAVERSION :=
endif

ifeq ($(SUPERIOR_BUILDTYPE), UNOFFICIAL)
    ifneq ($(TARGET_UNOFFICIAL_BUILD_ID),)
        SUPERIOR_EXTRAVERSION := -$(TARGET_UNOFFICIAL_BUILD_ID)
    endif
endif

SUPERIOR_VERSION_SUFFIX := $(SUPERIOR_BUILD_DATE)-$(SUPERIOR_BUILDTYPE)$(SUPERIOR_EXTRAVERSION)-$(SUPERIOR_BUILD)

# Internal version
SUPERIOR_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(SUPERIOR_VERSION_SUFFIX)

# Display version
SUPERIOR_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR)-$(SUPERIOR_VERSION_SUFFIX)

# SuperiorOS version properties
PRODUCT_SYSTEM_PROPERTIES += \
    ro.superior.version=$(SUPERIOR_VERSION) \
    ro.superior.display.version=$(SUPERIOR_DISPLAY_VERSION) \
    ro.superior.build.version=$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR) \
    ro.superior.releasetype=$(SUPERIOR_BUILDTYPE)
